<div id="footer-container">
    <div id="footer-links">
        CGI &copy; 2016. This site is hosted by <a href="http://www.ga.gov.au/">Geoscience Australia</a> but responsibility for the content of the site lies with <a href="http://www.cgi-iugs.org/">CGI</a> not with Geoscience Australia. Questions, suggestions or comments regarding the contents of this site should be directed to the <a href="mailto:CGIsecretariat@bgr.de">CGI secretariat</a>.
    </div>
</div>
</body>
</html>
