<div id="footer-container">
    <div id="footer-links">
        CGI &copy; 2017. This site is hosted by <a href="http://www.ga.gov.au/">Geoscience Australia</a> but responsibility and copyright for the site content lies with the <a href="http://www.cgi-iugs.org/">IUGS CGI</a>. Questions, suggestions or comments regarding the contents of this site should be directed to the <a href="mailto:CGIsecretariat@mail.cgs.gov.cn">CGI secretariat</a>.
    </div>
</div>
</body>
</html>
