<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>GeoSciML and GeoSciML-Portrayal</title>
    <link rel="stylesheet" href="/geosciml.org/theme/css/cgi_theme.css" />
    <link rel="stylesheet" href="/geosciml.org/theme/css/alternates.css" />
    <link rel="shortcut icon" href="/geosciml.org/theme/favicon.ico">
</head>
<body>
<div id="header">
    <table>
        <tr>
            <td>
                <a href="http://www.cgi-iugs.org/"><img src="/geosciml.org/theme/img/logo-iugs.png" height="100px"/></a>
                <a href="http://www.cgi-iugs.org/"><img src="/geosciml.org/theme/img/title.jpg" height="100px"/></a>
                <a href="http://www.geosciml.net"><img src="/geosciml.org/theme/img/logo-geosciml.png" height="100px"/></a>
            </td>
        </tr>
        <tr>
            <td>
                <div id="ga-nav">
                    <a href="/">GeoSciML Home</a>
                    <a href="http://www.cgi-iugs.org/">CGI Home</a>
                    <a href="http://resource.geosciml.org/def/voc/">CGI Resources</a>
                    <a href="http://schemas.geosciml.org">CGI Schemas</a>
                </div>
            </td>
        </tr>
    </table>
    <div id="ga-colour-strip-container">
        <div id="ga-colour-strip"></div>
    </div>
</div>
