<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>GeoSciML</title>
    <link rel="stylesheet" href="<?php print $WEB_FOLDER; ?>theme/css/cgi_theme.css" />
    <link rel="stylesheet" href="<?php print $WEB_FOLDER; ?>theme/css/alternates.css" />
    <link rel="shortcut icon" href="<?php print $WEB_FOLDER; ?>theme/favicon.ico">
</head>
<body>
<div id="header">
    <table>
        <tr>
            <td style="text-align:center;">
                <a href="http://www.cgi-iugs.org/"><img src="<?php print $WEB_FOLDER; ?>theme/img/logo-iugs.png" height="75px"/></a>
                <a href="http://www.cgi-iugs.org/"><img src="<?php print $WEB_FOLDER; ?>theme/img/title.jpg" height="75px"/></a>
                <a href="http://www.geosciml.org"><img src="<?php print $WEB_FOLDER; ?>theme/img/logo-geosciml.png" height="75px"/></a>
            </td>
        </tr>
        <tr>
            <td>
                <div id="ga-nav">
                        <a href="http://www.cgi-iugs.org">CGI Home</a> |
			<a href="http://www.geosciml.org">GeoSciML Home</a> |
			<a href="http://external.opengeospatial.org/twiki_public/GeoSciMLswg/WebHome">GeoSciML Wiki</a> |
			<a href="http://www.earthresourceml.org">EarthResourceML</a> |
                        <a href="http://resource.geosciml.org">Vocabularies</a>
                </div>
            </td>
        </tr>
    </table>
    <div id="ga-colour-strip-container">
        <div id="ga-colour-strip"></div>
    </div>
</div>
