<div id="rightMenu" style="display:block; float:right; width:300px; background-color:#E5E5E5; padding:5px;">
    <ul>
        <li><a href="http://www.geosciml.net">Home</a>
        <li><a href="http://www.cgi-iugs.org/tech_collaboration/geosciml.html">Introduction to GeoSciML</a></li>
        <li><a href="http://schemas.geosciml.net">GeoSciML schemas</a></li>
        <li><a href="http://resource.geosciml.net">Geoscience vocabularies</a></li>
        <li><a href="http://www.opengeospatial.org/projects/groups/geoscimlswg">GeoSciML Standards Working Group (SWG)</a></li>
        <li><a href="http://external.opengeospatial.org/twiki_public/GeoSciMLswg/WebHome">GeoSciML SWG Wiki</a></li>
        <li><a href="http://www.earthresourceml.org">EarthResourceML</a></li>
        <li><a href="https://www.seegrid.csiro.au/wiki/CGIModel/WebHome">Wiki for earlier versions of GeoSciML</a></li>
    </ul>
    <div style="display:block; width:300px; min-height:150px; background-image:url(/geosciml.org/theme/img/map_image2.jpg);"></div>
</div><!-- #rightMenu -->
